  
spring:
  zipkin:
    base-url: http://localhost:9411/

  cloud:
    gateway:
      routes:
      - id: customer-details
        uri: lb://CUSTOMER-DETAIL
        predicates:
        - Path=/customer/**
      - id: customer-payments
        uri: lb://CUSTOMER-PAYMENT
        predicates:
        - Path=/payment/**             
    
    
    
  